# Build Flipper Zero Firmware using GitHub Actions
name: Build RogueMaster-NoAnim

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *

env:
  REPO_URL: https://github.com/RogueMaster/flipperzero-firmware-wPlugins
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  GIT_NAME: RogueMaster-NoAnim
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 检查项目分支
        uses: actions/checkout@v3

      - name: 编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          
      - name: 下载固件源码
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone --recursive $REPO_URL
          ln -sf /workdir/flipperzero-firmware-wPlugins $GITHUB_WORKSPACE/flipperzero-firmware-wPlugins

      - name: 清理Anim&增加power
        id: clean-anim
        run: |
          rm flipperzero-firmware-wPlugins/assets/dolphin/internal/wrenchathome_F0Pattern_128x64/*.png
          cp flipperzero-firmware-wPlugins/assets/dolphin/external/Kuronons_RMCFW_128x64/frame_0.png flipperzero-firmware-wPlugins/assets/dolphin/internal/wrenchathome_F0Pattern_128x64/
          sed -i '/^Passive framesc\Passive frames\: 1/g' flipperzero-firmware-wPlugins/assets/dolphin/internal/wrenchathome_F0Pattern_128x64/meta.txt
          sed -i '/^Frame ratec\Frame rate\: 1' flipperzero-firmware-wPlugins/assets/dolphin/internal/wrenchathome_F0Pattern_128x64/meta.txt
          sed -i '/^Frames orderc\Frames order\: 1/g' flipperzero-firmware-wPlugins/assets/dolphin/internal/wrenchathome_F0Pattern_128x64/meta.txt
          cat flipperzero-firmware-wPlugins/assets/dolphin/internal/wrenchathome_F0Pattern_128x64/meta.txt
          
          rm -rf flipperzero-firmware-wPlugins/assets/dolphin/external/*
          cp flipperzero-firmware-wPlugins/assets/dolphin/internal/manifest.txt flipperzero-firmware-wPlugins/assets/dolphin/external/
          sed -i '1,2!d' flipperzero-firmware-wPlugins/assets/dolphin/external/manifest.txt

          sed -i 's/power_limit = 12/power_limit = 53/g' flipperzero-firmware-wPlugins/firmware/targets/f7/furi_hal/furi_hal_region.c
          cat flipperzero-firmware-wPlugins/firmware/targets/f7/furi_hal/furi_hal_region.c
          

      - name: 编译固件
        id: compile
        run: |
          cd flipperzero-firmware-wPlugins/
          ./fbt updater_package
          echo "status=success" >>$GITHUB_OUTPUT 
          echo "FILE_TIME=$(date "+%Y.%m.%d-%H.%M")" >> $GITHUB_ENV
          echo "GIT_NAME=$GIT_NAME" >> $GITHUB_ENV
         
      - name: 检查磁盘使用情况
        if: (!cancelled())
        run: df -hT

      - name: 组织文件
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          cd flipperzero-firmware-wPlugins/dist/f7-C/
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT 
          
      - name: 上传固件目录
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: Flipper_firmware$GIT_NAME${{ env.FILE_TIME }}
          path: ${{ env.FIRMWARE }}

      - name: 生成release标签
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "release_tag=${{ env.FILE_TIME }}_$GIT_NAME" >>$GITHUB_OUTPUT 
          touch release.txt
          echo "[源码来源]($REPO_URL)" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT 
          
      - name: 上传固件到release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.FILE_TIME }}_${{ env.GIT_NAME }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 150
          keep_minimum_runs: 200

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 2000
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
