# Build Flipper Zero Firmware using GitHub Actions
name: Build Unleashed

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      anim:
        required: false
        default: 'no'
        type: choice
        description: Need Anim ?
        options: 
        - 'yes'
        - 'no'
  schedule:
    - cron: 30 23 * * *

env:
  REPO_URL: https://github.com/DarkFlippers/unleashed-firmware
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  GIT_NAME: Unleashed
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 检查项目分支
        uses: actions/checkout@v3

      - name: 编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          [ github.event.inputs.anim == 'yes' ] && echo "FILE_NAME=$GIT_NAME" >> $GITHUB_ENV
          [ github.event.inputs.anim == 'no' ] && echo "FILE_NAME=$GIT_NAME-NoAnim" >> $GITHUB_ENV

      - name: 下载固件源码
        id: download
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone --recursive $REPO_URL
          ln -sf /workdir/unleashed-firmware $GITHUB_WORKSPACE/Flipper
          echo "status=success" >> $GITHUB_OUTPUT

      - name: SSH连接管理
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: 默认配置
        id: setting
        if: steps.download.outputs.status == 'success' && !cancelled()
        run: |
          sed -i 's/false/true/g' Flipper/assets/resources/subghz/assets/dangerous_settings
          cp ./files/setting_user.txt Flipper/assets/resources/subghz/assets/
          sed -i 's/430000000/430000000,430500000/g' Flipper/lib/subghz/subghz_setting.c
          sed -i 's/431500000/431500000,432800000/g' Flipper/lib/subghz/subghz_setting.c
          sed -i 's/430000000/430000000,430500000/g' Flipper/applications/main/subghz/views/subghz_frequency_analyzer.c
          sed -i 's/431500000/431500000,432800000/g' Flipper/applications/main/subghz/views/subghz_frequency_analyzer.c
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 清理Anim
        id: clean
        if: github.event.inputs.anim == 'no' && steps.setting.outputs.status == 'success' && !cancelled()
        run: |
          shopt -s extglob
          cp ./files/meta.txt Flipper/assets/dolphin/internal/L1_Tv_128x47/
          rm Flipper/assets/dolphin/internal/L1_Tv_128x47/*.png
          cp ./files/frame_0.png Flipper/assets/dolphin/internal/L1_Tv_128x47/
          rm -rf Flipper/assets/dolphin/external/!("manifest.txt")
          sed -i '1,2!d' Flipper/assets/dolphin/external/manifest.txt

      - name: 编译固件
        id: compile
        if: steps.setting.outputs.status == 'success' && !cancelled()
        run: |
          cd Flipper/
          ./fbt updater_package
          echo "FILE_TIME=$(date "+%Y%m%d-%H%M")" >> $GITHUB_ENV
          echo "FILE_DATE=$(date "+%Y%m%d")" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 检查磁盘使用情况
        if: (!cancelled())
        run: df -hT

      - name: 组织文件
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd Flipper/dist/f7-D/
          rm -rf *.tgz
          mv f7-update-* "${{ env.FILE_NAME }}-${{ env.FILE_TIME }}"
          tar -czf "${{ env.FILE_NAME }}-${{ env.FILE_TIME }}.tgz" "${{ env.FILE_NAME }}-${{ env.FILE_TIME }}"
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 上传固件目录
        uses: actions/upload-artifact@main
        if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ${{ env.FILE_NAME }}-${{ env.FILE_TIME }}
          path: ${{ env.FIRMWARE }}

      - name: 生成ReleaseTag
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
        run: |
          echo "release_tag=${{ env.FILE_DATE }}-${{ env.GIT_NAME }}" >> $GITHUB_OUTPUT 
          touch release.txt
          echo "[源码来源]($REPO_URL)" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT 

      - name: 上传固件到Release
        uses: softprops/action-gh-release@v1
        if: env.UPLOAD_RELEASE == 'true' && steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.FILE_DATE }}_${{ env.GIT_NAME }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*.tgz

      - name: Delete workflow runs
        uses: FunctionXJB/delete-workflow-runs@main
        with:
          retain_days: 30
          keep_minimum_runs: 100

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 20
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
