# Build Flipper Zero Firmware using GitHub Actions
name: Build Xtreme-NoAnim

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 30 0 * * *

env:
  REPO_URL: https://github.com/ClaraCrazy/Flipper-Xtreme
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  GIT_NAME: Xtreme-NoAnim
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 检查项目分支
        uses: actions/checkout@v3

      - name: 编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo apt install rename
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "GIT_NAME=$GIT_NAME" >> $GITHUB_ENV
          
      - name: 下载固件源码
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone --recursive $REPO_URL
          ln -sf /workdir/Flipper-Xtreme $GITHUB_WORKSPACE/Flipper-Xtreme

      - name: SSH连接管理
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: 增加power&默认配置
        id: add-power
        run: |
          sed -i 's/power_limit = 12/power_limit = 53/g' Flipper-Xtreme/firmware/targets/f7/furi_hal/furi_hal_region.c
          sed -i 's/431500000/431500000,432800000/g' Flipper-Xtreme/lib/subghz/subghz_setting.c
          sed -i 's/431500000/431500000,432800000/g' Flipper-Xtreme/applications/main/subghz/views/subghz_frequency_analyzer.c
          
      - name: 清理Anim
        id: clean-anim
        run: |
          shopt -s extglob
          sed -i '1,2!d' Flipper-Xtreme/assets/dolphin/custom/WatchDogs/Anims/manifest.txt

          rm -rf Flipper-Xtreme/assets/dolphin/external/!("L1_Furippa1_128x64"|"manifest.txt")
          sed -i '1,9!d' Flipper-Xtreme/assets/dolphin/external/manifest.txt
          sed -i 's/L1_Waves_128x50/L1_Furippa1_128x64/g' Flipper-Xtreme/assets/dolphin/external/manifest.txt
          
          rm -rf Flipper-Xtreme/assets/dolphin/external/L1_Furippa1_128x64/*
          cp ./files/meta.txt Flipper-Xtreme/assets/dolphin/external/L1_Furippa1_128x64/
          cp ./files/frame_0.png Flipper-Xtreme/assets/dolphin/external/L1_Furippa1_128x64/
    
      - name: 编译固件
        id: compile
        run: |
          cd Flipper-Xtreme/
          ./fbt updater_package
          echo "status=success" >>$GITHUB_OUTPUT 
          echo "FILE_TIME=$(date "+%Y%m%d-%H%M")" >> $GITHUB_ENV
          
      - name: 检查磁盘使用情况
        if: (!cancelled())
        run: df -hT

      - name: 组织文件
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          cd Flipper-Xtreme/dist/f7-C/
          rename -v 's/flipper-z-f7/Flipper-${{ env.GIT_NAME }}-${{ env.FILE_TIME }}/' *.*
          rename -v 's/_\d+//' *.*
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >>$GITHUB_OUTPUT 
          
      - name: 上传固件目录
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: Flipper_firmware$GIT_NAME${{ env.FILE_TIME }}
          path: ${{ env.FIRMWARE }}

      - name: 生成release标签
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "release_tag=${{ env.GIT_NAME }}" >>$GITHUB_OUTPUT 
          touch release.txt
          echo "[源码来源]($REPO_URL)" >> release.txt
          echo "status=success" >>$GITHUB_OUTPUT 
          
      - name: 上传固件到release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.FILE_TIME }}_${{ env.GIT_NAME }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*.tgz

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 150
          keep_minimum_runs: 20

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 20
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
