# Build Flipper Zero Firmware using GitHub Actions
name: Build Xtreme

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      anim:
        required: false
        default: 'NoAnim'
        type: choice
        description: Need Anim ?
        options: 
        - 'NoAnim'
        - 'Anim'
  schedule:
    - cron: '35 3-23/4 * * ?'

env:
  GITHUB_URL: https://github.com/
  REPO_URL: Flipper-XFW/Xtreme-Firmware
  GIT_NAME: Xtreme

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 检查库更新情况
        id: checknew
        run: |
          curl https://api.github.com/repos/$REPO_URL > index.json
          echo $(date +%s)
          echo $(date +%s -d "$(cat index.json | grep "pushed_at" | head -n 1 | sed 's/  "updated_at": "//g' | sed 's/\",//g' | sed 's/Z//g' | sed 's/T/ /g')")
          echo $(($(date +%s) - $(date +%s -d "$(cat index.json | grep "pushed_at" | head -n 1 | sed 's/  "updated_at": "//g' | sed 's/\",//g' | sed 's/Z//g' | sed 's/T/ /g')")))
          if [ $(($(date +%s) - $(date +%s -d "$(cat index.json | grep "pushed_at" | head -n 1 | sed 's/  "updated_at": "//g' | sed 's/\",//g' | sed 's/Z//g' | sed 's/T/ /g')"))) -le 14400 ]
            then
              echo "IFNEW=TRUE" >> $GITHUB_ENV
              echo "status=success" >> $GITHUB_OUTPUT
          else
              echo "IFNEW=FALSE" >> $GITHUB_ENV
              echo "No Update"
          fi

      - name: 检查项目分支
        id: check
        if: steps.checknew.outputs.status == 'success' && !cancelled()
        uses: actions/checkout@v4

      - name: 编译环境
        id: environment
        if: steps.checknew.outputs.status == 'success' && !cancelled()
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "FILE_TIME=$(date "+%Y%m%d-%H%M")" >> $GITHUB_ENV
          echo "FILE_DATE=$(date "+%Y%m%d")" >> $GITHUB_ENV
          echo "TIME_HOUR=$(date "+%k")" >> $GITHUB_ENV
          echo "FILE_NAME=$GIT_NAME" >> $GITHUB_ENV

      - name: 下载固件源码
        id: download
        if: steps.checknew.outputs.status == 'success' && !cancelled()
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone --recursive $GITHUB_URL/$REPO_URL
          ln -sf /workdir/Xtreme-Firmware $GITHUB_WORKSPACE/Flipper
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 默认配置
        id: setting
        if: steps.download.outputs.status == 'success' && !cancelled()
        run: |
          sed -i 's/power_limit = 12/power_limit = 12/g' Flipper/targets/f7/furi_hal/furi_hal_region.c
          sed -i 's/430000000/430000000,430500000/g' Flipper/lib/subghz/subghz_setting.c
          sed -i 's/431500000/431500000,432800000/g' Flipper/lib/subghz/subghz_setting.c
          sed -i 's/430000000/430000000,430500000/g' Flipper/applications/main/subghz/views/subghz_frequency_analyzer.c
          sed -i 's/431500000/431500000,432800000/g' Flipper/applications/main/subghz/views/subghz_frequency_analyzer.c
          echo "status=success" >> $GITHUB_OUTPUT
          
      - name: 清理Anim
        if: ${{ env.TIME_HOUR }}!=6 && steps.setting.outputs.status == 'success' && github.event.inputs.anim != 'Anim' && !cancelled()
        id: clean
        run: |
          shopt -s extglob
          rm -rf Flipper/assets/packs/WatchDogs/Icons
          rm -rf Flipper/assets/packs/WatchDogs/Anims/!("manifest.txt")
          sed -i '1,2!d' Flipper/assets/packs/WatchDogs/Anims/manifest.txt
          rm -rf Flipper/assets/dolphin/external/!("L1_Furippa1_128x64"|"manifest.txt")
          sed -i '1,9!d' Flipper/assets/dolphin/external/manifest.txt
          sed -i 's/L1_Waves_128x50/L1_Furippa1_128x64/g' Flipper/assets/dolphin/external/manifest.txt
          rm -rf Flipper/assets/dolphin/external/L1_Furippa1_128x64/*
          cp ./files/meta.txt Flipper/assets/dolphin/external/L1_Furippa1_128x64/
          cp ./files/frame_0.png Flipper/assets/dolphin/external/L1_Furippa1_128x64/
          echo "FILE_NAME=$GIT_NAME-NoAnim" >> $GITHUB_ENV

      - name: 清理SD
        if: steps.setting.outputs.status == 'success' && !cancelled()
        id: cleanSD
        run: |
          rm -rf Flipper/assets/resources/wav_player
          rm -rf Flipper/assets/resources/music_player
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 编译固件
        id: compile
        if: steps.cleanSD.outputs.status == 'success' && !cancelled()
        run: |
          cd Flipper/
          ./fbt updater_package
          echo "FILE_TIME=$(date "+%Y%m%d-%H%M")" >> $GITHUB_ENV
          echo "FILE_DATE=$(date "+%Y%m%d")" >> $GITHUB_ENV
          echo "GIT_NAME=$GIT_NAME" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 检查磁盘使用情况
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: df -hT

      - name: 组织文件
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd Flipper/dist/f7-C/
          rm -rf *.tgz
          mv f7-update-* "${{ env.FILE_NAME }}-${{ env.FILE_TIME }}"
          tar --delete asset_packs -vf ${{ env.FILE_NAME }}-${{ env.FILE_TIME }}/resources.tar
          tar -czf "${{ env.FILE_NAME }}-${{ env.FILE_TIME }}.tgz" "${{ env.FILE_NAME }}-${{ env.FILE_TIME }}"
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT 

      - name: 上传固件目录
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ${{ env.GIT_NAME }}-${{ env.FILE_TIME }}
          path: ${{ env.FIRMWARE }}

      - name: 生成ReleaseTag
        id: tag
        if: steps.organize.outputs.status == 'success' && !cancelled()
        run: |
          echo "release_tag=${{ env.FILE_DATE }}-${{ env.GIT_NAME }}" >> $GITHUB_OUTPUT 
          touch release.txt
          echo "[源码来源]($GITHUB_URL/$REPO_URL)" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT 
          
      - name: 上传固件到Release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.FILE_DATE }}_${{ env.GIT_NAME }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*.tgz

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: 3000
          delete_workflows: true
          workflows_keep_day: 365
          gh_token: ${{ secrets.GH_TOKEN }}
